version: '3.8'

services:
  app:
    build: .
    container_name: flight_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mycoolappdb
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && python main.py"
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: flight_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mycoolappdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mycoolappdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: