"""initial112

Revision ID: 3545efb4ede6
Revises: 
Create Date: 2025-04-09 06:56:35.769007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3545efb4ede6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('aircraft_model', sa.String(length=50), nullable=True),
    sa.Column('airline', sa.String(length=100), nullable=True),
    sa.Column('flight_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('callsign', sa.String(length=20), nullable=False),
    sa.Column('icao24', sa.String(length=20), nullable=True),
    sa.Column('aircraft_code', sa.String(length=10), nullable=True),
    sa.Column('airline', sa.String(length=100), nullable=True),
    sa.Column('airline_code', sa.String(length=10), nullable=True),
    sa.Column('airline_icao', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('origin_airport', sa.String(length=10), nullable=True),
    sa.Column('destination_airport', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_callsign'), 'flights', ['callsign'], unique=False)
    op.create_index(op.f('ix_flights_icao24'), 'flights', ['icao24'], unique=False)
    op.create_index(op.f('ix_flights_timestamp'), 'flights', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_timestamp'), table_name='flights')
    op.drop_index(op.f('ix_flights_icao24'), table_name='flights')
    op.drop_index(op.f('ix_flights_callsign'), table_name='flights')
    op.drop_table('flights')
    op.drop_table('flight_stats')
    # ### end Alembic commands ###
